# version: "3.1"

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
       POSTGRES_PASSWORD: example
       POSTGRES_DB: bondis_app
       POSTGRES_USER: docker

  # redis:
  #   image: bitnami/redis:latest
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
         

